# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='imagerprofile',
            managers=[
            ],
        ),
    ]
