# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=imager_images.models.user_directory_path)),
            ],
        ),
    ]
