# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20160426_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos'),
        ),
    ]
