# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160411_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(default=models.CharField(default=None, max_length=255)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(default=models.CharField(default=None, max_length=255)),
        ),
    ]
