# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0008_auto_20160413_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bleh', models.CharField(max_length=10)),
            ],
        ),
    ]
