# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0009_bogusmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BogusModel',
        ),
    ]
